"""initial schema

Revision ID: 494b7dbe5d37
Revises: 
Create Date: 2026-04-02 12:47:01.911575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494b7dbe5d37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("site_name", sa.String(), nullable=True),
        sa.Column("duration_minutes", sa.Float(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_logs_id"), "activity_logs", ["id"], unique=False)

    op.create_table(
        "pomodoro_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pomodoro_sessions_id"), "pomodoro_sessions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pomodoro_sessions_id"), table_name="pomodoro_sessions")
    op.drop_table("pomodoro_sessions")

    op.drop_index(op.f("ix_activity_logs_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
