"""added task_name to sessions

Revision ID: 4fd97d904010
Revises: 494b7dbe5d37
Create Date: 2026-04-02 13:15:27.579805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd97d904010'
down_revision: Union[str, Sequence[str], None] = '494b7dbe5d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoro_sessions', sa.Column('task_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoro_sessions', 'task_name')
    # ### end Alembic commands ###
