"""remove task_name from pomodoro_sessions

Revision ID: 6fc1970b32e8
Revises: 4fd97d904010
Create Date: 2026-04-02 13:37:22.421017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc1970b32e8'
down_revision: Union[str, Sequence[str], None] = '4fd97d904010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoro_sessions', 'task_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoro_sessions', sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
